feat: support more zil eco projects
Zilliqa/zil-ecosystem pull request #15
Opened 2021-11-02 09:02 UTC by renlulu

2021-11-04 05:02 UTC, AshIgnYeo requested changes

2021-11-04 05:02 UTC, AshIgnYeo commented on projects/xanpool/project.md
> +---
Xanpool seems to have some formatting issues. frontmatter doesn't appear properly

2021-11-15 11:02 UTC, AmritKumar commented on projects/valkyrie/project.md
> +categories: false
```suggestion
categories: fund
```

2021-11-15 11:03 UTC, AmritKumar commented on projects/valkyrie/project.md
> +twitter: False
```suggestion
twitter: https://twitter.com/ValkyrieFunds
```

2021-11-15 11:03 UTC, AmritKumar commented on projects/valkyrie/project.md
> +website: False
```suggestion
website: https://valkyrieinvest.com/
```

2021-11-15 11:39 UTC, AshIgnYeo approved these changes

2021-11-15 11:39 UTC, merged