Fixed Readme.md
Zilliqa/zil-ecosystem pull request #36
Opened 2021-11-30 13:19 UTC by hicaru

* fixed a link to twitter

2021-12-21 08:25 UTC, AshIgnYeo requested changes

2021-12-21 08:25 UTC, AshIgnYeo commented on projects/dragonzil/project.md
> +twitter: twitter.com/zildragons
please include uri scheme "http", "https"

2022-08-11 13:19 UTC, Elliott-Green approved these changes

2023-01-09 16:56 UTC, rrw-zilliqa commented
Now so old that I'm going to close it - please re-open if still relevant.

2023-01-09 16:56 UTC, closed without merging