add beanterra
Zilliqa/zil-ecosystem pull request #53
Opened 2022-02-17 11:40 UTC by jianesis

2022-02-22 08:50 UTC, AshIgnYeo requested changes

2022-02-22 08:50 UTC, AshIgnYeo commented on projects/beanterra/project.md
> +date: 2 Dec 2022
@jianesis can you confirm this date?

2022-02-23 06:51 UTC, jianesis commented on projects/beanterra/project.md
> +date: 2 Dec 2022
Yes this is confirmed

2022-02-24 03:11 UTC, AshIgnYeo approved these changes

2022-02-24 03:11 UTC, merged